services:
  nominatim:
    image: mediagis/nominatim:5.1
    container_name: nominatim
    networks:
      - app-decide_default
    expose:
      - "8080:8080"
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/belgium-latest.osm.pbf
    restart: unless-stopped
    volumes:
      - ./nominatim-data:/var/lib/postgresql/16/main

  geocoding-service:
    container_name: geocoding-service
    build:
      context: .
    ports:
      - "8082:80"
    networks:
      - app-decide_default
    environment:
      MODE: "development"
      LOG_LEVEL: "debug"
      MU_SPARQL_ENDPOINT: http://app-decide-virtuoso-1:8890/sparql
      NOMINATIM_BASE_URL: http://nominatim:8080
      NER_LABELS: '["CITY", "DOMAIN", "HOUSENUMBERS", "INTERSECTION", "POSTCODE", "PROVINCE", "ROAD", "STREET"]'
    volumes:
      - ./:/app

networks:
  app-decide_default:
    external: true
