services:
  nominatim:
    image: mediagis/nominatim:5.1
    container_name: nominatim
    networks:
      - decide
    expose:
      - "8080:8080"
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/belgium-latest.osm.pbf
    restart: unless-stopped
    volumes:
      - ./nominatim-data:/var/lib/postgresql/16/main

  geocoding-service:
    container_name: geocoding-service
    build:
      context: .
    ports:
      - "8081:80"
    networks:
      - decide
    environment:
      MODE: "development"
      LOG_LEVEL: "debug"
      MU_SPARQL_ENDPOINT: http://virtuoso:8890/sparql
      NOMINATIM_BASE_URL: http://nominatim:8080
      NER_LABELS: '["CITY", "DOMAIN", "HOUSENUMBERS", "INTERSECTION", "POSTCODE", "PROVINCE", "ROAD", "STREET"]'
      OPENAI_API_KEY: 'sk-SECRET-PART'
      LLM_MODEL_NAME: 'gpt-4o-mini'
      LLM_TEMPERATURE: 0.1
    volumes:
      - ./:/app

networks:
  decide:
    external: true
