services:
  demo:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: demo
    ports:
      - "8501:8501"
    environment:
      - NOMINATIM_URL=http://nominatim:8080
    restart: unless-stopped
  nominatim:
    image: mediagis/nominatim:5.1
    container_name: nominatim
    expose:
      - "8080:8080"
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/belgium-latest.osm.pbf
    restart: unless-stopped
